### ISSUE TITLE
Fails on bazel 0.21.0 on OSX

### ISSUE THREAD

**Issue by DarkDimius** [jmillikin/rules_bison#1]
```
b3f74fd65c8a/external/parser/BUILD.bazel:10:1: in bison_cc_library rule @parser//:bison_parser:
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_dmitry/9878c75bb785aeb934f7b3f74fd65c8a/external/parser/BUILD.bazel", line 10
		bison_cc_library(name = 'bison_parser')
	File "/private/var/tmp/_bazel_dmitry/9878c75bb785aeb934f7b3f74fd65c8a/external/io_bazel_rules_bison/bison/bison.bzl", line 457, in _bison_cc_library
		_build_cc_info(ctx, result.source, result.header)
	File "/private/var/tmp/_bazel_dmitry/9878c75bb785aeb934f7b3f74fd65c8a/external/io_bazel_rules_bison/bison/bison.bzl", line 404, in _build_cc_info
		cc_toolchain.needs_pic_for_dynamic_libraries(feature_configuration = ld_featu...)
type 'CcToolchainInfo' has no method needs_pic_for_dynamic_libraries(feature_configuration feature_configuration)
```

**Comment by jmillikin** [comment]
Nothing I can do about this, sorry. The `bison_cc_library` rule has a hard dependency on the new C++ toolchain, which is available in Bazel v0.22. It's scheduled to release next week (https://github.com/bazelbuild/bazel/issues/6494) so either wait until then, or use the `bison()` rule and define the `cc_library` separately:

```python
bison(
    name = "parser_srcs",
    src = "parser.y",
)
cc_binary(
    name = "parser",
    srcs = [":parser_srcs"],
)
```
